# Generated by Django 2.0.2 on 2018-09-18 07:31

import API.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='お客様ID')),
                ('client_name', models.CharField(max_length=32, verbose_name='お客様名')),
                ('license_num', models.IntegerField(verbose_name='購入ライセンス数')),
                ('service_start_date', models.DateTimeField(verbose_name='契約開始日')),
                ('service_expire_date', models.DateTimeField(verbose_name='次回契約更新タイミング')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_name', models.CharField(max_length=32, verbose_name='テナント名')),
                ('billing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='テナントID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='トランザクションID')),
                ('watson_id', models.CharField(max_length=36, verbose_name='WatsonユーザーID')),
                ('requested_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='変換日時')),
                ('recognized_seconds', models.FloatField(verbose_name='変換秒数')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that user id already exists.'}, help_text='Required. 32 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_monitor', models.BooleanField(default=False, help_text='Designates whether the user can see transaction status.', verbose_name='トランザクション閲覧権限')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('watson_id', models.CharField(max_length=36, verbose_name='WatsonユーザーID')),
                ('watson_pass', models.CharField(max_length=12, verbose_name='Watsonパスワード')),
                ('login_status', models.BooleanField(default=False, verbose_name='ログインステータス')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='管理者')),
                ('billing_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Tenant', verbose_name='請求先テナント')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', API.models.UserManager()),
            ],
        ),
    ]
