# Generated by Django 2.0.2 on 2018-09-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20180918_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.ClientInfo', verbose_name='お客様名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_monitor',
            field=models.BooleanField(default=False, help_text='トランザクションを参照できるかどうかを指定します。', verbose_name='トランザクション閲覧権限'),
        ),
    ]
