# Generated by Django 2.0.2 on 2018-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20180918_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dict_used',
            field=models.BooleanField(default=False, verbose_name='辞書'),
        ),
    ]
